apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: #{service-domain}#-hpa
  namespace: #{namespace}#
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: #{service-domain}#-deployment
  minReplicas: #{min-replicas-hpa}#
  maxReplicas: #{max-replicas-hpa}#
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: #{cpu-hpa}#